### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reiz** [marthie/SSLReport#2]
Without a license it's not really open source. You should add a license information to the pom.xml. I would recommend the MIT license. 

```
  <licenses>
    <license>
      <name>MIT</name>
      <url>http://choosealicense.com/licenses/mit/</url>
    </license>
  </licenses>
```

**Comment by reiz** [comment]
The MIT license says that everybody, private persons & corporations, are allowed to use your software without restrictions. They can even use it in commercial closed source software. The license also says that your code is WITHOUT WARRANTY OF ANY KIND. That means your are not reliable for bugs ;-) 

If you just want that everybody is using your project then the MIT license is the right license for you. 

The license you choose does **not** effect your dependencies. You have to take care that the licenses of your dependencies are compatible to the license you picked. In that case MIT. You can do that by hand or use a service for that, for example [VersionEye](https://www.versioneye.com).

**Comment by reiz** [comment]
Another cool license is the [Unlicense](http://unlicense.org/). It sets your code under the public domain. That means you give up any rights on the IP and everybody can do without what ever he/she wants without warranty.

**Comment by reiz** [comment]
I pulled your pom.xml into VersionEye. Your dependencies are all up-to-date and the licenses are all compatible to the MIT. See your project [here](https://www.versioneye.com/user/projects/55a560783735380012000044#tab-licenses). Only `bcprov-jdk16 : 1.46` is marked as red because the Bouncy Castle License is not on my whitelist. But I double checked that license and it is the text from the MIT license. Will put that on my whitelist.

**Comment by marthie** [comment]
Thanks Robert! 
I going to set MIT license for this project.
